#!/bin/bash

echo "GitHubへのプッシュには認証が必要です。"
echo ""
echo "以下の手順でプッシュしてください："
echo ""
echo "1. GitHubアクセストークンを作成："
echo "   - https://github.com/settings/tokens にアクセス"
echo "   - 'Generate new token (classic)' をクリック"
echo "   - 'repo' スコープを選択"
echo "   - トークンをコピー"
echo ""
echo "2. 以下のコマンドを実行："
echo "   git push -u origin main"
echo ""
echo "3. 入力を求められたら："
echo "   Username: dicekitoh"
echo "   Password: [アクセストークンを貼り付け]"
echo ""
echo "または、トークンを含むURLでプッシュ："
echo "git remote set-url origin https://dicekitoh:YOUR_TOKEN@github.com/dicekitoh/macmini2014-python-tools.git"
echo "git push -u origin main"